### ISSUE TITLE
Can't build it with my Angular app. Please help me how to fix this. Thanks.

### ISSUE THREAD

**Issue by NIkhilbadveli** [erikh2000/sl-ogg#1]
✘ [ERROR] Could not resolve "fs"

    node_modules/sl-web-ogg/dist/index.es.js:21:18:
      21 │   var Z = require("fs"),
         ╵                   ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    node_modules/sl-web-ogg/dist/index.es.js:22:16:
      22 │     H = require("path");
         ╵                 ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

**Comment by erikh2000** [comment]
I've noticed a problem like this earlier. I'll see if I can get a repro again.

**Comment by NIkhilbadveli** [comment]
From my hours of research, I understood that it's because the middle layer code has some portion where it's using require statements to import the 'fs' and 'path' node packages, which won't be available in a browser environment. But, I can't seem to fix this problem though.

**Comment by NIkhilbadveli** [comment]
Never mind. I managed to fork your repo (I hope that's alright) and remove the problematic part. And it's working now. Thanks anyway.

https://github.com/NIkhilbadveli/custom-ogg-encoder.git

**Comment by erikh2000** [comment]
Nice. I will see if I can benefit from your fix in my codebase. I see your change in 'wasm/middle-layer.js'.

`middle-layer.js` is generated by Emscripten, so I don't want to just delete the section of code there. I'll take a look at Emscripten to see if it has options for generating the JS without the NodeJs stuff.

**Comment by erikh2000** [comment]
And no worries about forking, of course. Fork away, my brother.

**Comment by erikh2000** [comment]
I changed my WASM build script to generate a middle-layer.js that shouldn't depend on Node.

@NIkhilbadveli your direct-edit approach is good unless you want to to rebuld the WASM later--then emscripten will overwrite your changes to middle-layer.js.

**Comment by NIkhilbadveli** [comment]
Cool. Thanks. I just needed the encoder to work when I deploy my app. I am not likely to rebuild the wasm middle layer.
